### ISSUE TITLE
Beacuse some chinese can not be shown, I need the Encoding of this plugin.

### ISSUE THREAD

**Issue by Someone999** [OsuSync/IngameOverlay#6]
![bug](https://user-images.githubusercontent.com/45456778/93861667-76e20d80-fcf3-11ea-8aec-2ba93df5d6d4.png)

**Comment by Someone999** [comment]
I'm using UTF-8

**Comment by Deliay** [comment]
You selected font is missing some glyph like '寂' or '寞', try another font
