### ISSUE TITLE
crash problem

### ISSUE THREAD

**Issue by lokillo-0** [OsuSync/IngameOverlay#7]
when i inject the overlay into the game it causes a crash

https://www.youtube.com/watch?v=5PF7fFKpf_8

**Comment by Deliay** [comment]
A update for 'ortdp' was released, run update command again maybe resolve this problem

**Comment by lokillo999** [comment]
Yeah Is fixed thanks

**Comment by lokillo-0** [comment]
Yeah is fixed thanks
