### ISSUE TITLE
PP Counter Breaking

### ISSUE THREAD

**Issue by Vehzx** [OsuSync/IngameOverlay#8]
Hi, had this issue a few months back and it was fixed with an update, seems it has returned.

Upon injecting the overlay, it works fine at the menu, maps update, showing PP correctly, then you load a map and while playing nothing shows where the PP counter should be, just empty boxes.

I tried installing the patch files and running those, still nothing. I then did 'plugins update' and then when updating it closes and re opens sync, as if it has finished the update for the PP displayer, but then doing plugins update again will show there is still an update for the PP displayer.

**Comment by MikiraSora** [comment]
you can go [here](https://github.com/OsuSync/RealTimePPDisplayer/releases) ,download latest release zip , and then extract to Sync folder
