### ISSUE TITLE
Halloween Update broke Sync

### ISSUE THREAD

**Issue by Yuri146** [OsuSync/IngameOverlay#9]
I was using sync flawlessly, until new Update came out. Now my hit-displayer isn't being displayed at all. I tried to update Sync, to fresh-install Sync, but nothing helped.

**Comment by Deliay** [comment]
A update for 'ortdp' was released, run update command again maybe resolve this problem

**Comment by gamernoob24** [comment]
it never appear


edit: i repaired it myself and the problem is just the administrator privileges
